# Generated by Django 5.2 on 2025-05-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(choices=[('j', 'Jedda'), ('r', 'Riyadh'), ('m', 'Macca')], default='j', max_length=1),
        ),
    ]
